include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - lib/core/data/local/tm_database.g.dart
  
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: false
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_catches_without_on_clauses: false
    avoid_types_on_closure_parameters: false
    avoid_returning_this: false
    type_annotate_public_apis: false